-- Application-owned half of a user's identity (see §2 of
-- application-user-identity-management.md). userId is generated by the application
-- (never by Postgres) and is the canonical identifier referenced by the matching
-- Keycloak account, so it is not a generated/serial column here.
--
-- Roles are deliberately not modeled here: Keycloak recomputes realm_access.roles on every
-- token issuance (including silent refresh), so authorization reads roles from the token
-- rather than a local mirror. Only account status needs a local, per-request check, since a
-- revocation must block an already-issued, still-valid token immediately (UF-IDU-13).

CREATE TABLE application_user
(
    user_id    UUID PRIMARY KEY,
    email      VARCHAR(255) NOT NULL,
    status     VARCHAR(20)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_application_user_email UNIQUE (email)
);
